<font color=muave>1.Write a function to compute 5/0 and use try/except to catch the exceptions.</font>

In [11]:
def div(x,y):
    try:
        result=x//y
        print("Result of x/y is:",result)
    except:
        print("we have divided by 0.")

In [12]:
div(9,5)

Result of x/y is: 1


In [13]:
div(1,0)

we have divided by 0.


<font color=muave>2.Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].</font>

<font color=muave>Hint: Subject,Verb and Object should be declared in the program as shown below.</font>

<font color=muave>subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]</font>

In [18]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["baseball.","Cricket."]
sentences=[(sub+" "+vb+" "+obj) for sub in subjects for vb in verbs for obj in objects]
for sent in sentences:
    print(sent)

Americans play baseball.
Americans play Cricket.
Americans watch baseball.
Americans watch Cricket.
Indians play baseball.
Indians play Cricket.
Indians watch baseball.
Indians watch Cricket.


<font color=muave>3.Write a function so that the columns of the output matrix are powers of the input vector.


<font color=muave>The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

<font color=muave>HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.</font>

In [5]:
import numpy as np
x=np.array([1,2,3,4,5])
n=3
np.vander(x,n)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [6]:
j=np.array([1,2,3,4])
np.vander(j)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [7]:
np.column_stack([n*[n - i - 1] for i in range(n)])

array([[2, 1, 0],
       [2, 1, 0],
       [2, 1, 0]])